### ISSUE TITLE
Page not scaling correctly

### ISSUE THREAD

**Issue by LunaticBFF57** [TempeHS/2023IST-Website-Crawford.Lieu#3]
Having this issue on my phone.
(Doing this so I remember)

**Comment by DefNotCrawf** [comment]
Still not working as of 9/3/2023 @ 10:00 PM (UTC+11)

**Comment by DefNotCrawf** [comment]
@benpaddlejones, yeah, it works on dev options, but it doesn't render correctly on my phone for some reason.

**Comment by DefNotCrawf** [comment]
Kinda works now
